#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: ./send_telegram_text.sh [--dry-run] [message]

Sends a text message through the Telegram Bot API.

Credentials:
  TELEGRAM_BOT_TOKEN | TG_BOT_TOKEN | BOT_TOKEN | TELEGRAM_TOKEN
  TELEGRAM_CHAT_ID   | TG_CHAT_ID   | CHAT_ID   | TELEGRAM_TO

Message sources:
  1. first positional argument
  2. TELEGRAM_MESSAGE, TELEGRAM_TEXT, MESSAGE_TEXT, or MESSAGE
  3. autogenerated automation ping

Options:
  --dry-run              Print the payload without contacting Telegram
  -h, --help             Show this help text
USAGE
}

first_non_empty() {
  while (($# > 0)); do
    if [[ -n "${1:-}" ]]; then
      printf '%s' "$1"
      return 0
    fi
    shift
  done
  return 1
}

dry_run=0

while (($# > 0)); do
  case "$1" in
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      break
      ;;
  esac
done

bot_token="$(first_non_empty "${TELEGRAM_BOT_TOKEN:-}" "${TG_BOT_TOKEN:-}" "${BOT_TOKEN:-}" "${TELEGRAM_TOKEN:-}" || true)"
chat_id="$(first_non_empty "${TELEGRAM_CHAT_ID:-}" "${TG_CHAT_ID:-}" "${CHAT_ID:-}" "${TELEGRAM_TO:-}" || true)"
message="$(first_non_empty "${1:-}" "${TELEGRAM_MESSAGE:-}" "${TELEGRAM_TEXT:-}" "${MESSAGE_TEXT:-}" "${MESSAGE:-}" || true)"

if [[ -z "$message" ]]; then
  message="Automation ping from $(hostname) at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
fi

if [[ "$dry_run" -eq 1 ]]; then
  echo "Dry run: Telegram text message would be sent."
  echo "Message: $message"
  if [[ -n "$chat_id" ]]; then
    echo "Chat ID: $chat_id"
  fi
  exit 0
fi

if [[ -z "$bot_token" ]]; then
  echo "Error: missing Telegram bot token. Set TELEGRAM_BOT_TOKEN." >&2
  exit 1
fi

if [[ -z "$chat_id" ]]; then
  echo "Error: missing Telegram chat ID. Set TELEGRAM_CHAT_ID." >&2
  exit 1
fi

response="$(
  curl --silent --show-error --fail-with-body \
    --request POST \
    --data-urlencode "chat_id=${chat_id}" \
    --data-urlencode "text=${message}" \
    --data-urlencode "disable_web_page_preview=true" \
    "https://api.telegram.org/bot${bot_token}/sendMessage"
)"

if [[ "$response" =~ \"ok\"[[:space:]]*:[[:space:]]*true ]]; then
  echo "Telegram text message sent."
else
  echo "Telegram API returned an unexpected response:" >&2
  echo "$response" >&2
  exit 1
fi
