#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  send_telegram_text.sh [--dry-run] [message]

Credentials (any supported name):
  TELEGRAM_BOT_TOKEN | BOT_TOKEN | TELEGRAM_TOKEN
  TELEGRAM_CHAT_ID   | CHAT_ID   | TELEGRAM_TO

Message inputs:
  1) first positional arg
  2) TELEGRAM_TEXT
  3) MESSAGE_TEXT
  4) MESSAGE
  5) autogenerated default message

Optional:
  TELEGRAM_PARSE_MODE / PARSE_MODE        (MarkdownV2, Markdown, HTML)
  TELEGRAM_THREAD_ID / MESSAGE_THREAD_ID  (forum topic thread id)

Examples:
  ./send_telegram_text.sh "Hello from automation"
  TELEGRAM_TEXT="Daily report ready" ./send_telegram_text.sh
  ./send_telegram_text.sh --dry-run "Preview only"
EOF
}

first_non_empty() {
  while (($# > 0)); do
    if [[ -n "${1:-}" ]]; then
      printf '%s' "$1"
      return 0
    fi
    shift
  done
  return 1
}

DRY_RUN=0
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
  shift
fi

BOT_TOKEN="$(first_non_empty "${TELEGRAM_BOT_TOKEN:-}" "${BOT_TOKEN:-}" "${TELEGRAM_TOKEN:-}" || true)"
CHAT_ID="$(first_non_empty "${TELEGRAM_CHAT_ID:-}" "${CHAT_ID:-}" "${TELEGRAM_TO:-}" || true)"

MESSAGE="$(first_non_empty "${1:-}" "${TELEGRAM_TEXT:-}" "${MESSAGE_TEXT:-}" "${MESSAGE:-}" || true)"
if [[ -z "$MESSAGE" ]]; then
  MESSAGE="Automation ping from $(hostname) at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
fi

PARSE_MODE="$(first_non_empty "${TELEGRAM_PARSE_MODE:-}" "${PARSE_MODE:-}" || true)"
THREAD_ID="$(first_non_empty "${TELEGRAM_THREAD_ID:-}" "${MESSAGE_THREAD_ID:-}" || true)"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "Dry run: Telegram message would be sent."
  echo "Message: $MESSAGE"
  if [[ -n "$CHAT_ID" ]]; then
    echo "Chat ID: $CHAT_ID"
  fi
  if [[ -n "$PARSE_MODE" ]]; then
    echo "Parse mode: $PARSE_MODE"
  fi
  if [[ -n "$THREAD_ID" ]]; then
    echo "Thread ID: $THREAD_ID"
  fi
  exit 0
fi

if [[ -z "$BOT_TOKEN" ]]; then
  echo "Error: missing bot token. Set TELEGRAM_BOT_TOKEN (or BOT_TOKEN / TELEGRAM_TOKEN)." >&2
  exit 1
fi

if [[ -z "$CHAT_ID" ]]; then
  echo "Error: missing chat id. Set TELEGRAM_CHAT_ID (or CHAT_ID / TELEGRAM_TO)." >&2
  exit 1
fi

API_URL="https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"

CURL_ARGS=(
  --silent
  --show-error
  --fail-with-body
  --request POST
  --data-urlencode "chat_id=${CHAT_ID}"
  --data-urlencode "text=${MESSAGE}"
  --data-urlencode "disable_web_page_preview=true"
)

if [[ -n "$PARSE_MODE" ]]; then
  CURL_ARGS+=(--data-urlencode "parse_mode=${PARSE_MODE}")
fi

if [[ -n "$THREAD_ID" ]]; then
  CURL_ARGS+=(--data-urlencode "message_thread_id=${THREAD_ID}")
fi

RESPONSE="$(curl "${CURL_ARGS[@]}" "$API_URL")"

if [[ "$RESPONSE" =~ \"ok\"[[:space:]]*:[[:space:]]*true ]]; then
  echo "Telegram message sent successfully."
else
  echo "Telegram API returned an unexpected response:" >&2
  echo "$RESPONSE" >&2
  exit 1
fi
